# ITMAL Exercise

REVISIONS||
---------||
2018-1218| CEF, initial.                  
2019-0131| CEF, spell checked and update. 
2019-0204| CEF, changed d1/d2 in Qb to L1/L2. Fixe rev date error.
2019-0204| CEF, changed headline.
2019-0204| CEF, changed (.) in dist(x,y) to use pipes instead.
2019-0204| CEF, updated supervised learning fig, and changed , to ; for thetas, and change = to propto
2019-0205| CEF, post lesson update, minor changes, added fabs around two test vectors.
2019-0207| CEF, updated def section. 
2019-0901| CEF, updated for ITMAL v2.
2019-0904| CEF, updated for print-f and added conclusion Q.
2019-0905| CEF, fixed defect in print string and commented on fabs.
2020-0130| CEF, F20 ITMAL update.
2020-0203| CEF, minor text fixes.
2020-0224| CEF, elaborated on MAE and RMSE, emphasized not to use np functionalty in L1 and L2.

## Mathematical Foundation

### Vector and matrix representation in python

Say, we have $d$ features for a given sample point. This $d$-sized feature column vector for a data-sample $i$ is then given by

$$
    \newcommand\rem[1]{}
    \rem{ITMAL: CEF def and LaTeX commands, remember: no newlines in defs}
    \newcommand\eq[2]{#1 &=& #2\\}
    \newcommand\ar[2]{\begin{array}{#1}#2\end{array}}
    \newcommand\ac[2]{\left[\ar{#1}{#2}\right]}
    \newcommand\st[1]{_{\scriptsize #1}}
    \newcommand\norm[1]{{\cal L}_{#1}}
    \newcommand\obs[2]{#1_{\mbox{\scriptsize obs}}^{\left(#2\right)}}
    \newcommand\diff[1]{\mbox{d}#1}
    \newcommand\pown[1]{^{(#1)}}
    \def\pownn{\pown{n}}
    \def\powni{\pown{i}}
    \def\powtest{\pown{\mbox{\scriptsize test}}}
    \def\powtrain{\pown{\mbox{\scriptsize train}}}
    \def\bX{\mathbf{M}}
    \def\bX{\mathbf{X}}
    \def\bZ{\mathbf{Z}}
    \def\bw{\mathbf{m}}
    \def\bx{\mathbf{x}}
    \def\by{\mathbf{y}}
    \def\bz{\mathbf{z}}
    \def\bw{\mathbf{w}}
    \def\btheta{{\boldsymbol\theta}}
    \def\bSigma{{\boldsymbol\Sigma}}
    \def\half{\frac{1}{2}}
\bx\powni = 
    \ac{c}{
        x_1\powni \\
        x_2\powni \\ 
        \vdots \\
        x_d\powni
     }  
$$

or typically written transposed to save as

$$
    \bx\powni = \left[  x_1\powni~~ x_2\powni~~ \cdots~~ x_d\powni\right]^T
$$

The full data matrix $\bX$ is then constructed out of $n$ samples of these feature vectors

$$
    \bX =
        \ac{cccc}{
            x_1\pown{1} & x_2\pown{1} & \cdots & x_d\pown{1} \\
            x_1\pown{2} & x_2\pown{2} & \cdots & x_d\pown{2}\\
            \vdots      &             &        & \vdots \\
            x_1\pownn   & x_2\pownn   & \cdots & x_d\pownn\\
        }
$$

such that $\bX$ can be expressed as

$$
    \bX = 
      \ac{c}{
        (\bx\pown{1})^T \\
        (\bx\pown{2})^T \\
        \vdots \\
        (\bx\pownn)^T
      }
$$

but sometimes the notation is a little more fuzzy, leaving out the transpose operator for $\mathbf x$ and in doing so just interpreting the $\mathbf{x}^{(i)}$'s to be row vectors instead of column vectors.

The target column vector, $\mathbf y$, also has the dimension $n$ 

$$
    \by = \ac{c}{
            y\pown{1} \\
            y\pown{2} \\
            \vdots \\
            y\pownn \\
          }
$$

#### Qa Given the following $\mathbf{x}^{(i)}$'s, construct and print the $\mathbf X$ matrix in python.

$$
    \ar{rl}{
      \bx\pown{1} &= \ac{c}{ 1, 2, 3}^T \\
      \bx\pown{2} &= \ac{c}{ 4, 2, 1}^T \\
      \bx\pown{3} &= \ac{c}{ 3, 8, 5}^T \\
      \bx\pown{4} &= \ac{c}{-9,-1, 0}^T
    }
$$

##### Implementation Details

Notice that the ```np.matrix``` class is getting deprecated! So, we use numpy's ```np.array``` as matrix container. Also, __do not__ use the built-in python lists or the numpy matrix subclass.

In [99]:
# Qa

import numpy as np

y = np.array([1,2,3,4]) # NOTE:  you'll need this later



x_1=np.array([1,2,3])
x_2=np.array([4,2,1])
x_3=np.array([3,8,5])
x_4=np.array([-9,-1,0])
X = np.concatenate([[x_1], [x_2], [x_3],[x_4]])

print(np.transpose(X))

[[ 1  4  3 -9]
 [ 2  2  8 -1]
 [ 3  1  5  0]]


### Norms, metrics or distances

The $\norm{2}$ Euclidian distance, or norm, for a vector of size $n$ is defined as 

$$
    \norm{2}:~~ ||\bx||_2 = \left( \sum_{i=1}^{n} |x_i|^2 \right)^{1/2}\\
$$

and the distance between two vectors is given by

$$
    \ar{ll}{      
          d(\bx,\by) &= ||\bx-\by||_2\\
                     &= \left( \sum_{i=1}^n \left| x_{i}-y_{i} \right|^2 \right)^{1/2}
    }
$$ 

This Euclidian norm is sometimes also just denoted as $||\bx||$, leaving out the 2 in the subscript.

The squared $\norm{2}$ for a vector can compactly be expressed via 

$$
    \norm{2}^2: ||\bx||_2^2 = \bx^\top\bx
$$

by the general dot or inner-product (taking $\by=\bx$ in the $\norm{2}^2$ above)

$$
    \ar{ll}{
        \langle\bx,\by\rangle &= \bx\cdot\by\\ 
                              &=\bx^\top \by\\
                              &= \sum_{i=1}^n x_{i} y_{i} \\
                              &= ||\bx|| ~ ||\by|| \cos{\theta}
    }
$$

taking $\theta$ to be zero, and hence $cos(\theta)=1$ when calculating $\langle\bx,\bx\rangle$

The $\norm{1}$ 'City-block' norm is given by

$$
    \norm{1}:~~ ||\bx||_1 = \sum_i |x_i|
$$

but $\norm{1}$ is not used as intensive as its more popular $\norm{2}$ cousin. 

Notice that $|x|$ in code means ```fabs(x)```.

#### Qb Implement the $\norm{1}$ and $\norm{2}$ norms for vectors in python.

First implementation must be a 'low-level'/explicit implementation---using primitive/build-in functions, like ```+```, ```*``` and power ```**``` only! The square-root function can be achieved via power like ```x**0.5```.

Do NOT use any methods from libraries, like ```math.sqrt```, ```math.abs```, ```numpy.linalg.inner```, ```numpy.dot()``` or similar. Yes, using such libraries is an efficient way of building python software, but in this exercise we want to explicitly map the mathematichal formulaes to python code.

Name your functions L1 and L2 respectively, they both take one vector as input argument.

But test your implementation against some built-in functions, say  ```numpy.linalg.norm```

When this works, and passes the tests below, optimize the $\norm{2}$, such that it uses np.numpy's dot operator instead of an explicit sum, call this function L2Dot. This implementation must be pythonic, i.e. it must not contain explicit for- or while-loops.

In [93]:
import numpy as np
import math

def L1(vec):
    assert vec.ndim == 1
    vec = (vec**2)**0.5 #Square all numbers and then take square root to get magnitude
    return sum(vec) # Using built-in python sum function

def L2(vec):
    assert vec.ndim == 1
    dp = vec @ vec
    return dp ** 0.5

# Alternative implementation for L2
#def L2(vec):
#    assert vec.ndim == 1
#    vec = vec ** 2
#    return sum(vec)**0.5

def L2Dot(vec):  
    assert vec.ndim == 1
    dp = np.dot(vec, vec)
    return dp ** 0.5
    
    

# TEST vectors: here I test your implementation...calling your L1() and L2() functions
tx=np.array([1, 2, 3, -1])
ty=np.array([3,-1, 4,  1])

print(L1(tx-ty))
print(L2(tx-ty))

expected_d1=8.0
expected_d2=4.242640687119285

d1=L1(tx-ty)
d2=L2(tx-ty)

print(f"tx-ty={tx-ty}, d1-expected_d1={d1-expected_d1}, d2-expected_d2={d2-expected_d2}")
eps=1E-9 # remember to import math for fabs
assert math.fabs(d1-expected_d1)<eps, "L1 dist seems to be wrong" 
assert math.fabs(d2-expected_d2)<eps, "L2 dist seems to be wrong" 

# comment-in once your L2Dot fun is ready...
d2dot=L2Dot(tx-ty)
print("d2dot-expected_d2=",d2dot-expected_d2)
assert math.fabs(d2dot-expected_d2)<eps, "L2Ddot dist seem to be wrong" 

8.0
4.242640687119285
tx-ty=[-2  3 -1 -2], d1-expected_d1=0.0, d2-expected_d2=0.0
d2dot-expected_d2= 0.0


## The cost function, $J$

Now, most ML algorithm uses norms or metrics internally when doing minimizations. Details on this will come later, but for now we need to know that an algorithm typically tries to minimize a given performance metric, the loss function, for all the input data, and implicitly tries to minimize the sum of all norms for the 'distances' between some predicted output, $y\st{pred}$ and the true output $y\st{true}$, with the distance between these typically given by the $\norm{2}$ norm

$$   
  \mbox{individual loss:}~~L\powni = d(y\st{pred}\powni,y\st{true}\powni)
$$ 

with $y\st{pred}\powni$, a scalar value, being the output from the hypothesis function, that maps the input vector $\bx\powni$ to a scalar

$$ 
    y_{pred}\powni = \hat{y}\powni = h(\bx\powni;\btheta)
$$

and the total loss, $J$ will be the sum over all $i$'s

$$
    \ar{rl}{
        J &= \frac{1}{n} \sum_{i=1}^{n} L\powni\\
        &= \frac{1}{n} \sum_{i=1}^{n} d( h(\bx\powni) , y\powni\st{true})
    }
$$


### Cost function in vector/matrix notation using $\norm{2}$

Remember the data-flow model for supervised learning

<img src="https://itundervisning.ase.au.dk/F20_itmal/L02/Figs/ml_simple_vector.png" style="width:500px">

Let us now express $J$ in terms of vectors and matrices instead of summing over individual scalars, and let's use $\norm{2}$ as the distance function

$$
    \ar{rl}{
        J(\bX,\by;\btheta) &= \frac{1}{n} \sum_{i=1}^{n} L\powni\\
        &= \frac{1}{n}\sum_{i=1}^{n} (h(\bx\powni) - \by\powni\st{true})^2\\
        &= \frac{1}{n} ||h(\bX) - \by\st{true} ||_2^2\\
        &= \frac{1}{n} ||\by\st{pred} - \by\st{true} ||_2^2\\
     }
$$

with the matrix-vector notation

$$ 
    \by_{pred} = \hat{\by} =  h(\bX;\btheta)
$$

#### Loss or Objective Function using the Mean Squared Error

This formulation is equal to the definition of the _mean-squared-error_, MSE (or indirectly also RMSE), here given in the general formulation for some random variable $Z$ 

$$
    \ar{rl}{
        \mbox{MSE} &= \frac{1}{n} \sum_{i=1}^{n} (\hat{Z}_i-Z_i)^2 = \frac{1}{n} SS\\
        \mbox{RMSE} &= \sqrt{\mbox{MSE}}\
    }
$$

with sum-of-squares (SS) is given simply by

$$
    \mbox{SS} = \sum_{i=1}^{n} (\hat{Z}_i-Z_i)^2\\
$$


So, using the $\norm{2}$ for the distance metric, is equal to saying that we want to minimize $J$ with respect to the MSE

$$
    \ar{rl}{
        J &= \mbox{MSE}(h(\bX), \by\st{true}) \\
          &= \mbox{MSE}(\by\st{pred}~, \by\st{true}) \\
          &= \mbox{MSE}(\hat{\by}, \by\st{true})
     }
$$

Note: when minimizing one can ignore the constant factor $1/n$ and it really does not matter if you minimize MSE or RMSE. Often $J$ is also multiplied by 1/2 to ease notation when trying to differentiate it.

$$
    \ar{rl}{
        J(\bX,\by\st{true};\btheta) &\propto \half ||\by\st{pred} - \by\st{true} ||_2^2 \\
          &\propto \mbox{MSE}
     }
$$

### MSE

Now, let us take a look on how you calculate the MSE.

The MSE uses the $\norm{2}$ norm internally, well, actually $||\cdot||^2_2$ to be precise, and basically just sums, means and roots the individual (scalar) losses (distances), we just saw before. 

And the RMSE is just an MSE with a final square-root call.

### Qc Construct the Root Mean Square Error (RMSE) function (Equation 2-1 [HOML]).

Call the function RMSE, and evaluate it using the $\bX$ matrix and $\by$ from Qa.

We implement a dummy hypothesis function, that just takes the first column of $\bX$ as its 'prediction'

$$
    h\st{dummy}(\bX) = \bX(:,0)
$$

Do not re-implement the $\norm{2}$ for the RMSE function, but call the '''L2''' function you just implemented internally in RMSE.

In [100]:
from math import fabs
def RMSE(hX, y):
    assert hX.ndim == 1
    assert y.ndim == 1
    return L2(hX-y)/2
    
    

# Dummy h function:
def h(X):    
    if X.ndim!=2:
        raise ValueError("excpeted X to be of ndim=2, got ndim=",X.ndim)
    if X.shape[0]==0 or X.shape[1]==0:
        raise ValueError("X got zero data along the 0/1 axis, cannot continue")
    return X[:,0]

# Calls your RMSE() function:
r=RMSE(h(X),y)

# TEST vector:
eps=1E-9
expected=6.57647321898295
print(f"RMSE={r}, diff={r-expected}")
assert fabs(r-expected)<eps, "your RMSE dist seems to be wrong" 

RMSE=6.576473218982953, diff=2.6645352591003757e-15


### MAE

#### Qd Similar construct the Mean Absolute Error (MAE) function (Equation 2-2 [HOML]) and evaluate it.

The MAE will algorithmic wise be similar to the MSE part from using the $\norm{1}$ instead of the $\norm{2}$ norm.

Again, re-implementation of the$\norm{1}$ is a no-go, call the '''L1''' instead internally i MAE.

In [104]:
def MAE(hX, y):
    assert hX.ndim == 1
    assert y.ndim == 1
    return L1(hX-y)/len(y) 
#Formula from https://heartbeat.fritz.ai/5-regression-loss-functions-all-machine-learners-should-know-4fb140e9d4b0


# Calls your MAE function:
r=MAE(h(X), y)

# TEST vector:
expected=3.75
print(f"MAE={r}, diff={r-expected}")
assert fabs(r-expected)<eps, "MAE dist seems to be wrong" 

MAE=3.75, diff=0.0


## Pythonic Code

### Robustness of Code

Data validity checking is an essential part of robust code, and in Python the 'fail-fast' method is used extensively: instead of lingering on trying to get the 'best' out of an erroneous situation, the fail-fast pragma will be very loud about any data inconsistencies at the earliest possible moment.

Hence robust code should include a lot of error checking, say as pre- and post-conditions (part of the design-by-contract programming) when calling a function: when entering the function you check that all parameters are ok (pre-condition), and when leaving you check the return parameter (post-conditions).  

Normally assert-checking or exception-throwing will do the trick just fine, with the exception method being more _pythonic_.

For the norm-function you could, for instance, test your input data to be 'vector' like, i.e. like

```python
    assert x.shape[0]>=0 and x.shape[1]==0
    
    if not x.ndim==1:
        raise some error
```
or similar.

#### Qe Robust Code 

Add error checking code (asserts or exceptions), that checks for right $\hat\by$-$\by$ sizes of the MSE and MAE functions.

Also add error checking to all you previously tested L2() and L1() functions, and re-run all your tests.

In [ ]:
#Look above

### Qf Conclusion

Now, conclude on all the exercise above. 

Write a short textual conclusion (max. 10- to 20-lines) that extract the _essence_ of the exercises: why did you think it was important to look at these particular ML concepts, and what was our overall learning outcome of the exercises (in broad terms).

In [ ]:
# We use these concepts to judge how well our model performs. It is very important to know how well
# a model performs, in order to optimize & improve your model. Therefore it is important to know how
# the functions we use works, in order to know exactly where to improve.
# (Kombineret med det Thomas og Henrik har skrevet ifht. aflevering).